language: php

before_script:
    - composer install --prefer-source --no-interaction

script: phpunit

matrix:
    allow_failures:
        - php: 7.4

    fast_finish: true

notifications:
    on_success: never
    on_failure: always
