language: php

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

script: phpunit

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm

    fast_finish: true

    notifications:
        on_success: never
        on_failure: always